### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by mturjak** [mturjak/rest-mvc#1]
TODO list:
- [x] add debugging outputs to certain breakpoints to follow the lifecycle of the app
- [ ] default API reply returning some basic info about the API/server in JSON format
- [ ] transform config file from defining constants into a object/members structure
- [x] use native Slim\View templating instead the mvc view system
- [ ] set up authentication
- [ ] set up login and session cookies in the web part
- [ ] add tests
